# Generated by Django 5.1.5 on 2025-07-19 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopp', '0002_product_order_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='blockAmount',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='blockPrice',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='wholesale',
            field=models.CharField(blank=True, choices=[('block', 'Block'), ('karobka', 'Karobka')], max_length=50, null=True),
        ),
    ]
